{% set name = "lupa" %}
{% set version = "2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lupa-{{ version }}.tar.gz
  sha256: 9a770a6e89576be3447668d7ced312cd6fd41d3c13c2462c9dc2c2ab570e45d9

build:
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  number: 0

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - pip
    - setuptools
    - lua
  run:
    - python

test:
  imports:
    - lupa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scoder/lupa
  summary: Python wrapper around Lua and LuaJIT
  description: |
    Lupa integrates the runtimes of Lua or LuaJIT2 into CPython. 
    It is a partial rewrite of LunaticPython in Cython with some
    additional features such as proper coroutine support.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/scoder/lupa
  doc_url: https://github.com/scoder/lupa/blob/master/README.rst

extra:
  recipe-maintainers:
    - lincrosenbach
    - mv-per
    - brnomendes
    - mediocretech
